import { NgModule } from '@angular/core';
import { HomeModule, UserAvatarModule } from '@carbon/icons-angular';

import {
  SideNavModule,
  HeaderModule,
  InputModule,
  CheckboxModule,
  ButtonModule,
  AccordionModule,
  TabsModule,
  DropdownModule,
  GridModule,
  ProgressIndicatorModule,
  RadioModule,
  SearchModule,
  SelectModule,
  DialogModule,
  PlaceholderModule,
  TableModule,
  LoadingModule,
  NFormsModule,
  TilesModule,
  ContentSwitcherModule,
  NotificationModule,
  FileUploaderModule,
  DatePickerModule,
  ComboBoxModule,
  ModalModule,
} from 'carbon-components-angular';

@NgModule({
  imports: [
    SideNavModule,
    HeaderModule,
    InputModule,
    CheckboxModule,
    ButtonModule,
    AccordionModule,
    TabsModule,
    DropdownModule,
    GridModule,
    ProgressIndicatorModule,
    RadioModule,
    SearchModule,
    SelectModule,
    DialogModule,
    PlaceholderModule,
    TableModule,
    LoadingModule,
    NFormsModule,
    TilesModule,
    ContentSwitcherModule,
    NotificationModule,
    FileUploaderModule,
    DatePickerModule,
    ComboBoxModule,
    ModalModule,
    HomeModule,
    UserAvatarModule
  ],
  exports: [
    SideNavModule,
    HeaderModule,
    InputModule,
    CheckboxModule,
    ButtonModule,
    AccordionModule,
    TabsModule,
    DropdownModule,
    GridModule,
    ProgressIndicatorModule,
    RadioModule,
    SearchModule,
    SelectModule,
    DialogModule,
    PlaceholderModule,
    TableModule,
    LoadingModule,
    NFormsModule,
    TilesModule,
    ContentSwitcherModule,
    NotificationModule,
    FileUploaderModule,
    DatePickerModule,
    ComboBoxModule,
    ModalModule,
    HomeModule,
    UserAvatarModule
  ]
})
export class CarbonModule {}
